### ISSUE TITLE
Fast-scroll-handle jumping issue

### ISSUE THREAD

**Issue by roylee0704** [emilsjolander/StickyListHeaders#123]
Referenced from the discussion of #110 , it seems that the fast-scroll-handle issue is not completely solved, the jumping issue is not there when the divider height is big, etc: 20dp. 

But when the divider height is set down to 1dp, the jumping issue came to obvious, especially when you slowly scroll through the list, it happens when divider hits the 'top wall'.

The quick fix to this is by removing the android:clipToPadding setting. However @androidmoney felt that this should not be the culprit but instead something is missing on isCalledFromSuper(). Any takers?

**Comment by risayew** [comment]
I use the version 2.5.2 of the library from maven and still have the Fast scroller jumping issue on androids <= 4.3
