### ISSUE TITLE
Fast scroll not showing current section

### ISSUE THREAD

**Issue by lukesleeman** [emilsjolander/StickyListHeaders#176]
If fast scroll is enabled on a standard ListView, the current section of the list displays as you scroll:

![device-2013-09-17-160737](https://f.cloud.github.com/assets/902252/1155056/1b88147e-1f61-11e3-9550-23b774ce8fc3.png)

However, if we use the same adapter with StickyListHeadersListView and enable fast scrolling on the wrapped ListView the current section does not display:

![device-2013-09-17-161700](https://f.cloud.github.com/assets/902252/1155060/488177d6-1f61-11e3-8390-8ff62b20e856.png)

**Comment by aniketsphinx** [comment]
@lukesleeman I have edited AdapterWrapper class by implementing SectionIndexer and override 
@Override
public int getPositionForSection(int section) {
    return ((SectionIndexer)mDelegate).getPositionForSection(section);
}

@Override
public int getSectionForPosition(int position) {
    return ((SectionIndexer)mDelegate).getSectionForPosition(position);
}

@Override
public Object[] getSections() {
    return ((SectionIndexer)mDelegate).getSections();
}


doesnot solve fast scroll issue

**Comment by lukesleeman** [comment]
@aniketsphinx - Not sure what is going on there.  Did you have a look at the pull request that Christian posted above?  Is are you working with a version of the sticky list header which includes Christians fix?

**Comment by aniketsphinx** [comment]
@lukesleeman yes, I go through the Christians fix and I have used latest sticky list header.
