### ISSUE TITLE
StickyListView padding not working on 4.0 and 4.1

### ISSUE THREAD

**Issue by krzysiekbielicki** [emilsjolander/StickyListHeaders#230]
Layout:

```
<se.emilsjolander.stickylistheaders.StickyListHeadersListView
    android:layout_height="match_parent"
    android:layout_width="match_parent" android:id="@+id/staggeredgrid" android:scrollbarStyle="outsideOverlay" android:paddingTop="8dp" android:paddingLeft="8dp" android:paddingRight="8dp"/>
```

doesn't have defined paddings on Samsung Galaxy Note 1 (4.0.3)
![screenshot403164419032063479](https://f.cloud.github.com/assets/541805/1481356/bc1d8058-46c7-11e3-9bb7-1a515bb5bc8b.png)
nor HTC Sensation (4.0.3) 
![screenshot8418999274919382908](https://f.cloud.github.com/assets/541805/1481368/0335d1f2-46c8-11e3-9062-3528098b2cc2.png)
nor Samsung Galaxy S3 (4.1.2) 
![screenshot2883761827944719959](https://f.cloud.github.com/assets/541805/1481393/ab168150-46c8-11e3-8d19-96f1290520cb.png)

On HTC Desire (2.3.7), Nexus 4 (4.3), Samsung Galaxy S4 (4.2.2)

**Comment by supervital** [comment]
I also had the same issue. The difference was in build types. On the debug works ok, on the release padding disappear. So, I just added -keep class se.emilsjolander.stickylistheaders.** {*;} , in proguard rules.
