### ISSUE TITLE
Keep current scroll position

### ISSUE THREAD

**Issue by papo2608** [emilsjolander/StickyListHeaders#258]
Hello,

I'm updating the StickyListView items with following lines of code: (ArrayAdapter)
adapter.clear()
adapter.addAll(T... items)
adapter.notifyDataSetChanged()

After that the ListView loses the current scroll position.

When I replace the StickyListView with the Android ListView it keeps the current scroll position.

Is it possible to keep the current scroll position after updating the items?

Btw. your lib is great ;).

**Comment by Sakshamgupta20** [comment]
when activity is destroyed we have to store the scrollable position so for that

public static int index = -1;
    public static int top = -1;

 @Override
    public void onPause() {
        super.onPause();
        index =list.getFirstVisiblePosition();
        View v = list.getChildAt(0);
        top = (v == null) ? 0 : (v.getTop() - list.getPaddingTop());
    }
    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putInt("index",index);
        outState.putInt("top",top);
    }

and then in onloadfinished/in oncreateview add  
 if(index != -1)
        {
            list.setSelectionFromTop( index, top);
        }
