### ISSUE TITLE
How to customize Fast Scroll Thumb drawable

### ISSUE THREAD

**Issue by mohammad8135** [emilsjolander/StickyListHeaders#275]
I was trying to customize fast scroll thumb drawable in several ways like setting style, scrollbarVerticalThumbDrawable, but it is not customized. Since it is not a listview originally, I could not find any proper way to change fast scroll thumb drawable. Could you give me a solution.

**Comment by engineers-bojan** [comment]
Is there a plan in the near by future to enable this property to be changed in runtime via code or should we consider implementing it somehow?
