### ISSUE TITLE
Import to my project with gradle

### ISSUE THREAD

**Issue by retuner87** [emilsjolander/StickyListHeaders#289]
Hi,

sorry but i'm new in using Gradle.
I can't import "compile 'se.emilsjolander:stickylistheaders:2.3.0'", Android Studio give me this error: Error:se.emilsjolander:stickylistheaders:2.3.0.

How can i use your library to my project?

Thanks in advance, regards
Mattia

**Comment by sumanamajumder** [comment]
After syncing the package in gradle dependencies a message comes error:Failed to resolve :se.emilsjolander:stickylistheaders:2.3.0 show in file and show in project structure
