### ISSUE TITLE
fixed size or wrap_content does not work in the header

### ISSUE THREAD

**Issue by juliocbcotta** [emilsjolander/StickyListHeaders#298]
Hi,
As you can see in the attached image, the header just does not respects the android:layout_width="wrap_content" parameter when it is on the top of the ListView

![device-2014-05-29-014613](https://cloud.githubusercontent.com/assets/70573/3114083/365afd04-e6ec-11e3-9bc4-d64d67801130.png)

here is my header layout

``` XML
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/list_item_tv_header"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:textColor="@android:color/white"
    android:padding="3dp"
    android:background="@drawable/list_item_header_drawable" />
```

background drawable list_item_header_drawable.xml

``` XML
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:dither="true"
    android:shape="rectangle">
    <corners android:radius="5dp" />
    <solid android:color="#33B5E5" />
</shape>

```

**Comment by LunevNF** [comment]
I have the same problem (v. 2.7.0).
I already set for header (TextView) wrap_content, but it's not working. I see always match_parent. How to resolve this problem, @emilsjolander  ?

**Comment by LunevNF** [comment]
I need to set wrap_content (width) for any state: sticky or not. :(
