### ISSUE TITLE
Use StickyListHeaders with FloatingActionButton?

### ISSUE THREAD

**Issue by pbouliou** [emilsjolander/StickyListHeaders#330]
Hi,

I'm trying to use stickyListHeaders with FaizMalkani/FloatingActionButton lib. But as the floating action button bind itself as a scroll listener to the listview, then headers are no more "sticky" ...
Any solutions?

**Comment by nbau21** [comment]
Late answer, but useful to others! Basically hide the fab if you hit the bottom of the list, and show if not.

        myList.setOnScrollListener(new AbsListView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(AbsListView view, int scrollState) {

            }

            @Override
            public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount) {
                int lastInScreen = firstVisibleItem + visibleItemCount;
                if (lastInScreen == totalItemCount) {
                    fab.hide(true);
                } else {
                    fab.show(true);
                }
            }
        });
