### ISSUE TITLE
mList.setStickyHeaderTopOffset() doesn't update header

### ISSUE THREAD

**Issue by af-kabramov** [emilsjolander/StickyListHeaders#363]
if you make something like this:

mList.setOnScrollListener(new AbsListView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(AbsListView view, int scrollState) {
            }

            @Override
            public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount) {
                int scrollTabY = getTabsScrollY();
                int transTab = Math.max(-scrollTabY, mMinTabsY);
                mTabActionBar.setTranslationY(transTab);

                int scrollSearchY = getSearchScrollY();
                int transSearch;
                transSearch = Math.max(-scrollSearchY, mMinSearchY + transTab);
                if (mList.getFirstVisiblePosition() >= 1) {
                    mSearchHeader.setTranslationY(Math.min(transSearch, mMinTabsY));
                    int newOffset = (mTabsHeight + mSearchHeight) + transSearch;
                    mList.setStickyHeaderTopOffset(newOffset);
                } else {
                    mSearchHeader.setTranslationY(transSearch);
                    mList.setStickyHeaderTopOffset(0);
                }
            }
        });

sticky header updates only after hitting another header or need to make mAdapter.notifyDataSetChanged();

**Comment by asymptotik** [comment]
I'm experiencing the same issue.

**Comment by asymptotik** [comment]
I created a pull request to fix this. #376

**Comment by milek** [comment]
@asymptotik have you encounter a problem with wrong header being replaced for old items just before hitting new? Happens to me only when scrolling down

**Comment by af-kabramov** [comment]
fixed in #376

**Comment by dinuscxj** [comment]
I tested, and not fixed !
