### ISSUE TITLE
I dont wanna index using alphabets. Can i index using strings? I want to display a listview of images with their captions. The captions should be sticky headers. how can i do this?

### ISSUE THREAD

**Issue by gayathri-nair03** [emilsjolander/StickyListHeaders#400]

**Comment by billionbucks** [comment]
@gayathri-nair03 did you got it working ?

**Comment by jamieoneill** [comment]
For anyone still looking for this.
As getHeaderId returns a long you can convert your "caption" string if you parse it to long.

@Override
    public long getHeaderId(int position) {
        //return string as header
        String myHeader= "String Header";
        //remove spaces if any
        myHeader= myHeader.replaceAll("\\s","");
        //parse and return
        return Long.parseLong(myHeader,36);
    }
