### ISSUE TITLE
OnItemClickListener not working on  version 2.7.0

### ISSUE THREAD

**Issue by sefiktemel** [emilsjolander/StickyListHeaders#440]
When after a button added to list item;
OnHeaderClickListener is working but **OnItemClickListener** is not working! 
I am using  **AdapterView.OnItemClickListener()**. 
Please help

**Comment by xckevin** [comment]
@sefiktemel maybe you should not use Button, but use TextView

**Comment by sefiktemel** [comment]
I fixed that with define a compoundView. That compoundView trigger's it's own listeners
