### ISSUE TITLE
notifyDataSetChanged() causes the currently stuck header to disappear

### ISSUE THREAD

**Issue by Hasanabbas** [emilsjolander/StickyListHeaders#80]
When I try to update my list by calling notifyDataSetChanged(), the currently stuck header disappears and only reappears when I scroll up beyond where it should be (so whenever it would become unstuck). This didn't happen in the previous version.

**Comment by gowong** [comment]
This bug is happening for me using the latest version 2.5.2.

**Comment by domsu** [comment]
Same here, please fix it :(

**Comment by phellipealexandre** [comment]
Same here. Using release version 2.7.0
